### PR TITLE
adds Gapfish GmbH

### PR DESCRIPTION
**Pull request by TPei**
Hey, 

we like to support juniors too :)

### CODE REVIEW

**Comment by Malwine** [comment]
Hi @TPei It would be cool if you could fill out this little [questionnaire](https://github.com/Malwine/support-juniors/blob/master/companies.md) So we get an idea about your company :relaxed:

**Comment by Malwine** [comment]
Hi @TPei May I ask you to add your company in the [README](https://github.com/Malwine/support-juniors/blob/master/README.md)  under **Companies with open junior positions** if you have them? :relaxed:

**Comment by TPei** [comment]
Like so? Or is it a bit redundant to have us everywhere?^^

**Comment by Malwine** [comment]
No, don't worry! That's a great overview. Thanks for supporting juniors and adding your company!
giphythanks

**Comment by TPei** [comment]
I'm just hoping to get cool new colleagues ;)

**Pull request merged**
