### PR TITLE
Add POSpulse

### PR DESCRIPTION
**Pull request by acid**

### CODE REVIEW

**Comment by Malwine** [comment]
Hi @acid ,
thank you for contributing.
If you don't mind please add a little description of your product and where you team is located. 
(I guess its Berlin but we made the repo more international just now.)

**Comment by acid** [comment]
Sure thing! Where would the right place for this be?

**Comment by Malwine** [comment]
You can comment here.
I know you - but not your company ;)

**Why do I ask you for this?**
At the moment we are in the process of figuring out how people can contribute to this repository. 
I was thinking about a checklist. Because we are running into the problem that companies want to be added or ask me personally if they can be added even though they don't support juniors art all.

**Comment by Malwine** [comment]
As a help I wrote some questions down here:
https://github.com/Malwine/support-juniors/issues/19

**Comment by Malwine** [comment]
Thank you! @acid 
giphy2

**Pull request merged**
