### PR TITLE
adding shipcloud.io

### PR DESCRIPTION
**Pull request by andrecedik**

### CODE REVIEW

**Comment by Malwine** [comment]
Dear @andrecedik 
In order to get to know your company can you please provide a short description on what your company product is and how you support juniors? 
Thanks so much!

**Comment by andrecedik** [comment]
Hi @Malwine 
thanks for the feedback. Is there a default way of specifying the short description? Since the README currently has no descriptions I wasn't sure how to you want it to be specified. 

Thanks

**Comment by Malwine** [comment]
@andrecedik 
I am currently in the process of discussing this in issue #19 
I will add some ideas there now. Please have a look :blush:

**Comment by andrecedik** [comment]
Hey @Malwine 
thanks for the link to issue #19. I've adjusted the companies file accordingly. If you need anything more just let me know.

**Comment by Malwine** [comment]
Thank you @andrecedik !

**Comment by Malwine** [comment]
Thank you @andrecedik 
beemo

**Pull request merged**
